### ISSUE TITLE
Feature request: hyperlinks on text

### ISSUE THREAD

**Issue by RackhamLeNoir** [citation-style-language/documentation#76]
Hi,

Hyperlinks are convenient in bibliographies to access the paper directly. However including the url as a text uses space, and is against what hyperlinks are all about. I would like to be able to add a hyperlink to the url field in the bibtex entry to the title for example. As far as I understood it is not currently possible with CSL.

Is it possible to add this feature in the future? Either add a url property to text, or add a sub-item url.

Thanks,

**Comment by danmackinlay** [comment]
Where is this hypothetical API document?

**Comment by bdarcus** [comment]
To be written.

**Comment by danmackinlay** [comment]
Got it. So, pull requests welcome.

While we are here, I will mention for posterity my own hack for CSL's lack of support for link text in HTML output, which is to apply a CSS style:

```css
#refs a {
    display: inline-block;
    max-width: 10em;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    padding-left: 2em;
    border-bottom: none;
    text-decoration: #CBF8DF;
    box-shadow: none;
    font-size: 80%;
}
```

That gets me the following:
This is not particularly accessible or pretty, but it does stop the 200-character  URLs from breaking the page and is all I personally have time for.
Maybe this kind of thing could go on the appendix?

![Screen Shot 2020-05-26 at 08 17 07](https://user-images.githubusercontent.com/21740/82845817-5367ab80-9f29-11ea-821e-e92ecab8ad87.png)
